# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_version5.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 0px solid rgb(100, 100, 100);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_top.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"border-bottom:1px solid white;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_top_right = QtWidgets.QFrame(self.frame_top)
        self.frame_top_right.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_top_right.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_top_right)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_btns = QtWidgets.QFrame(self.frame_top_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_btns.sizePolicy().hasHeightForWidth())
        self.frame_top_btns.setSizePolicy(sizePolicy)
        self.frame_top_btns.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_top_btns.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_label_top_btns.setMaximumSize(QtCore.QSize(16777215, 46137))
        self.frame_label_top_btns.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_10.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_icon_top_bar.setStyleSheet("border:none;")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setLineWidth(0)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_10.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_label_top_btns)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"margin-left: 5px;")
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_10.addWidget(self.label_title_bar_top)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(90, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_back = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    outline: none;\n"
"    border: none;\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16*16/Simple_PySide_Base-master (1)/Simple_PySide_Base-master/icons/16x16/cil-action-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_5.addWidget(self.btn_back)
        self.horizontalLayout_4.addWidget(self.frame_btns_right)
        self.verticalLayout_2.addWidget(self.frame_top_btns)
        self.horizontalLayout_3.addWidget(self.frame_top_right)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        self.frame_center.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_content_right = QtWidgets.QFrame(self.frame_center)
        self.frame_content_right.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_content_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_right.setObjectName("frame_content_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_content_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_content = QtWidgets.QFrame(self.frame_content_right)
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.btn_home = QtWidgets.QPushButton(self.page)
        self.btn_home.setGeometry(QtCore.QRect(250, 70, 100, 100))
        self.btn_home.setStyleSheet("\n"
"QPushButton{\n"
"border: none;\n"
"\n"
"image: url(:/newPrefix/cocktail_button.png);\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/cocktail_button_pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.btn_home.setText("")
        self.btn_home.setObjectName("btn_home")
        self.btn_monitor = QtWidgets.QPushButton(self.page)
        self.btn_monitor.setGeometry(QtCore.QRect(450, 70, 100, 100))
        self.btn_monitor.setStyleSheet("\n"
"QPushButton{\n"
"border: none;\n"
"    \n"
"    image: url(:/newPrefix/monitor_button.png);\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    \n"
"    border:none;\n"
"    image: url(:/newPrefix/monitor_button_pressed.png);\n"
"    outline: none;\n"
"}")
        self.btn_monitor.setText("")
        self.btn_monitor.setObjectName("btn_monitor")
        self.btn_parameter = QtWidgets.QPushButton(self.page)
        self.btn_parameter.setGeometry(QtCore.QRect(250, 220, 100, 100))
        self.btn_parameter.setStyleSheet("\n"
"QPushButton{\n"
"border: none;\n"
"    \n"
"    image: url(:/newPrefix/faders.png);\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/faders_button_pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.btn_parameter.setText("")
        self.btn_parameter.setObjectName("btn_parameter")
        self.btn_settings = QtWidgets.QPushButton(self.page)
        self.btn_settings.setGeometry(QtCore.QRect(450, 220, 100, 100))
        self.btn_settings.setStyleSheet("\n"
"QPushButton{\n"
"border: none;\n"
"    image: url(:/newPrefix/setting_button1.png);\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/setting_button1_pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.btn_settings.setText("")
        self.btn_settings.setObjectName("btn_settings")
        self.stackedWidget.addWidget(self.page)
        self.page_home = QtWidgets.QWidget()
        self.page_home.setStyleSheet("border:none;")
        self.page_home.setObjectName("page_home")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.page_home)
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 221, 341))
        self.label_2.setStyleSheet("image: url(:/newPrefix/beer_bottle4.png);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.beer_slider = QtWidgets.QSlider(self.frame_2)
        self.beer_slider.setGeometry(QtCore.QRect(480, 50, 60, 311))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.beer_slider.setFont(font)
        self.beer_slider.setStyleSheet("QSlider:vertical {\n"
"    min-width: 60px;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"background: rgba(124,222,242, 200);\n"
" \n"
" }\n"
"QSlider::add-page:vertical {\n"
" \n"
"background: rgba(246,193,1, 255);\n"
" \n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: white; \n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 15px;\n"
"    margin-left: -10px;\n"
"    margin-right: -10px;\n"
"   \n"
"background: rgba(246,193,1, 225);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"   background-color: rgba(246, 193, 1, 200);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.beer_slider.setMaximum(100)
        self.beer_slider.setSingleStep(5)
        self.beer_slider.setProperty("value", 70)
        self.beer_slider.setOrientation(QtCore.Qt.Vertical)
        self.beer_slider.setObjectName("beer_slider")
        self.start_button = QtWidgets.QPushButton(self.frame_2)
        self.start_button.setGeometry(QtCore.QRect(610, 160, 141, 81))
        font = QtGui.QFont()
        font.setFamily("휴먼엑스포")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.start_button.setFont(font)
        self.start_button.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgba(246, 193, 1, 225);\n"
"border-radius:30px;\n"
"    border:none;\n"
"    outline: none;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(246, 193, 1, 200);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.start_button.setObjectName("start_button")
        self.beer_progressbar = QtWidgets.QProgressBar(self.frame_2)
        self.beer_progressbar.setGeometry(QtCore.QRect(30, 30, 181, 331))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.beer_progressbar.setFont(font)
        self.beer_progressbar.setStyleSheet("\n"
"QProgressBar::chunk:vertical {\n"
"background-color: qlineargradient(spread:reflect, x1:0.506, y1:1, x2:1, y2:0, stop:0 rgba(124, 222, 242, 255), stop:1 rgba(124, 222, 242, 170));\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"}")
        self.beer_progressbar.setProperty("value", 30)
        self.beer_progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.beer_progressbar.setTextVisible(True)
        self.beer_progressbar.setOrientation(QtCore.Qt.Vertical)
        self.beer_progressbar.setObjectName("beer_progressbar")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(230, 30, 221, 341))
        self.label_4.setStyleSheet("image: url(:/newPrefix/beer_bottle4.png);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.beer_progressbar_2 = QtWidgets.QProgressBar(self.frame_2)
        self.beer_progressbar_2.setGeometry(QtCore.QRect(250, 40, 181, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.beer_progressbar_2.setFont(font)
        self.beer_progressbar_2.setStyleSheet("\n"
"QProgressBar::chunk:vertical {\n"
"background-color: qlineargradient(spread:reflect, x1:0.506, y1:1, x2:1, y2:0, stop:0 rgba(246, 193, 1, 255), stop:1 rgba(246, 193, 1, 170));\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"}")
        self.beer_progressbar_2.setProperty("value", 70)
        self.beer_progressbar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.beer_progressbar_2.setTextVisible(True)
        self.beer_progressbar_2.setOrientation(QtCore.Qt.Vertical)
        self.beer_progressbar_2.setObjectName("beer_progressbar_2")
        self.beer_progressbar_2.raise_()
        self.beer_progressbar.raise_()
        self.label_2.raise_()
        self.start_button.raise_()
        self.label_4.raise_()
        self.beer_slider.raise_()
        self.verticalLayout_6.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_home)
        self.page_monitor = QtWidgets.QWidget()
        self.page_monitor.setMaximumSize(QtCore.QSize(800, 16777215))
        self.page_monitor.setObjectName("page_monitor")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_monitor)
        self.horizontalLayout_8.setContentsMargins(1, 0, 1, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(self.page_monitor)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.drink1_image_label = QtWidgets.QLabel(self.frame)
        self.drink1_image_label.setGeometry(QtCore.QRect(22, 40, 181, 251))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.drink1_image_label.setFont(font)
        self.drink1_image_label.setStyleSheet("image: url(:/newPrefix/bottle.png);")
        self.drink1_image_label.setText("")
        self.drink1_image_label.setTextFormat(QtCore.Qt.AutoText)
        self.drink1_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drink1_image_label.setObjectName("drink1_image_label")
        self.drink2_image_label = QtWidgets.QLabel(self.frame)
        self.drink2_image_label.setGeometry(QtCore.QRect(182, 40, 171, 251))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.drink2_image_label.setFont(font)
        self.drink2_image_label.setStyleSheet("image: url(:/newPrefix/bottle.png);")
        self.drink2_image_label.setText("")
        self.drink2_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drink2_image_label.setObjectName("drink2_image_label")
        self.drink1_replace_button = QtWidgets.QPushButton(self.frame)
        self.drink1_replace_button.setGeometry(QtCore.QRect(52, 310, 121, 61))
        font = QtGui.QFont()
        font.setFamily("휴먼엑스포")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.drink1_replace_button.setFont(font)
        self.drink1_replace_button.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(124, 222, 242, 220);\n"
"border-radius:30px;\n"
"border:none;\n"
"outline: none;\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(85, 170, 180);\n"
"    border:none;\n"
"outline: none;\n"
"\n"
"}")
        self.drink1_replace_button.setCheckable(False)
        self.drink1_replace_button.setFlat(False)
        self.drink1_replace_button.setObjectName("drink1_replace_button")
        self.drink2_replace_button = QtWidgets.QPushButton(self.frame)
        self.drink2_replace_button.setGeometry(QtCore.QRect(212, 310, 121, 61))
        font = QtGui.QFont()
        font.setFamily("휴먼엑스포")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drink2_replace_button.setFont(font)
        self.drink2_replace_button.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(246, 193, 1, 220);\n"
"border-radius:30px;\n"
"    border:none;\n"
"outline: none;\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(246, 193, 1, 180);\n"
"    border:none;\n"
"outline: none;\n"
"\n"
"}")
        self.drink2_replace_button.setObjectName("drink2_replace_button")
        self.drink1_progressbar = QtWidgets.QProgressBar(self.frame)
        self.drink1_progressbar.setGeometry(QtCore.QRect(72, 50, 71, 231))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.drink1_progressbar.setFont(font)
        self.drink1_progressbar.setStyleSheet("QProgressBar {\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: transparent;\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"width: 15px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: rgba(124, 222, 242, 200);\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"}")
        self.drink1_progressbar.setProperty("value", 100)
        self.drink1_progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.drink1_progressbar.setTextVisible(False)
        self.drink1_progressbar.setOrientation(QtCore.Qt.Vertical)
        self.drink1_progressbar.setObjectName("drink1_progressbar")
        self.drink2_progressbar = QtWidgets.QProgressBar(self.frame)
        self.drink2_progressbar.setGeometry(QtCore.QRect(232, 50, 71, 231))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.drink2_progressbar.setFont(font)
        self.drink2_progressbar.setStyleSheet("QProgressBar {\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: transparent;\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"width: 15px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: rgba(246, 193, 1, 200);\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"}")
        self.drink2_progressbar.setProperty("value", 100)
        self.drink2_progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.drink2_progressbar.setTextVisible(False)
        self.drink2_progressbar.setOrientation(QtCore.Qt.Vertical)
        self.drink2_progressbar.setObjectName("drink2_progressbar")
        self.drink1_residual_label = QtWidgets.QLabel(self.frame)
        self.drink1_residual_label.setGeometry(QtCore.QRect(87, 180, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.drink1_residual_label.setFont(font)
        self.drink1_residual_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.drink1_residual_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drink1_residual_label.setObjectName("drink1_residual_label")
        self.drink2_residual_label = QtWidgets.QLabel(self.frame)
        self.drink2_residual_label.setGeometry(QtCore.QRect(240, 180, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.drink2_residual_label.setFont(font)
        self.drink2_residual_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.drink2_residual_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drink2_residual_label.setObjectName("drink2_residual_label")
        self.drink1_progressbar.raise_()
        self.drink2_progressbar.raise_()
        self.drink1_image_label.raise_()
        self.drink2_image_label.raise_()
        self.drink1_replace_button.raise_()
        self.drink2_replace_button.raise_()
        self.drink1_residual_label.raise_()
        self.drink2_residual_label.raise_()
        self.horizontalLayout_8.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.page_monitor)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.thermomter_image_label = QtWidgets.QLabel(self.frame_3)
        self.thermomter_image_label.setGeometry(QtCore.QRect(250, 70, 71, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.thermomter_image_label.setFont(font)
        self.thermomter_image_label.setStyleSheet("image: url(:/newPrefix/온도계.png);\n"
"border:none")
        self.thermomter_image_label.setText("")
        self.thermomter_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.thermomter_image_label.setObjectName("thermomter_image_label")
        self.now_temperature_qlcd = QtWidgets.QLCDNumber(self.frame_3)
        self.now_temperature_qlcd.setGeometry(QtCore.QRect(70, 50, 141, 131))
        self.now_temperature_qlcd.setStyleSheet("border: 3px solid white;")
        self.now_temperature_qlcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.now_temperature_qlcd.setProperty("value", 0.0)
        self.now_temperature_qlcd.setObjectName("now_temperature_qlcd")
        self.set_temperature_qlcd = QtWidgets.QLCDNumber(self.frame_3)
        self.set_temperature_qlcd.setGeometry(QtCore.QRect(70, 230, 141, 131))
        self.set_temperature_qlcd.setStyleSheet("border: 3px solid white;")
        self.set_temperature_qlcd.setObjectName("set_temperature_qlcd")
        self.set_temperature_down_button = QtWidgets.QPushButton(self.frame_3)
        self.set_temperature_down_button.setGeometry(QtCore.QRect(260, 300, 61, 61))
        self.set_temperature_down_button.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/아래삼각형.png);\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/아래삼각형_pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.set_temperature_down_button.setText("")
        self.set_temperature_down_button.setObjectName("set_temperature_down_button")
        self.set_temperature_up_button = QtWidgets.QPushButton(self.frame_3)
        self.set_temperature_up_button.setGeometry(QtCore.QRect(260, 230, 61, 61))
        self.set_temperature_up_button.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/위삼각형.png);\n"
"border: none;\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/위삼각형_preesed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.set_temperature_up_button.setText("")
        self.set_temperature_up_button.setObjectName("set_temperature_up_button")
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_monitor)
        self.page_parameter = QtWidgets.QWidget()
        self.page_parameter.setMaximumSize(QtCore.QSize(800, 16777215))
        self.page_parameter.setStyleSheet("border:none;")
        self.page_parameter.setObjectName("page_parameter")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_parameter)
        self.horizontalLayout_11.setContentsMargins(1, 0, 1, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_6 = QtWidgets.QFrame(self.page_parameter)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(200, 35, 181, 21))
        font = QtGui.QFont()
        font.setFamily("휴먼엑스포")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(20, 35, 181, 21))
        font = QtGui.QFont()
        font.setFamily("휴먼엑스포")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pump2_parameter_up01 = QtWidgets.QPushButton(self.frame_6)
        self.pump2_parameter_up01.setGeometry(QtCore.QRect(210, 240, 61, 61))
        self.pump2_parameter_up01.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/위삼각형.png);\n"
"border: none;\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/위삼각형_preesed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.pump2_parameter_up01.setText("")
        self.pump2_parameter_up01.setObjectName("pump2_parameter_up01")
        self.pump1_parameter_up05 = QtWidgets.QPushButton(self.frame_6)
        self.pump1_parameter_up05.setGeometry(QtCore.QRect(120, 240, 61, 61))
        self.pump1_parameter_up05.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/위삼각형2.png);\n"
"border: none;\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/위삼각형2_pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.pump1_parameter_up05.setText("")
        self.pump1_parameter_up05.setObjectName("pump1_parameter_up05")
        self.pump2_parameter_down01 = QtWidgets.QPushButton(self.frame_6)
        self.pump2_parameter_down01.setGeometry(QtCore.QRect(210, 310, 61, 61))
        self.pump2_parameter_down01.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/아래삼각형.png);\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/아래삼각형_pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.pump2_parameter_down01.setText("")
        self.pump2_parameter_down01.setObjectName("pump2_parameter_down01")
        self.pump1_parameter_down05 = QtWidgets.QPushButton(self.frame_6)
        self.pump1_parameter_down05.setGeometry(QtCore.QRect(120, 310, 61, 61))
        self.pump1_parameter_down05.setStyleSheet("QPushButton{\n"
"border: none;\n"
"    \n"
"    image: url(:/newPrefix/아래삼각형2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/아래삼각형2 _pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.pump1_parameter_down05.setText("")
        self.pump1_parameter_down05.setObjectName("pump1_parameter_down05")
        self.pump2_parameter = QtWidgets.QLCDNumber(self.frame_6)
        self.pump2_parameter.setGeometry(QtCore.QRect(220, 80, 141, 151))
        self.pump2_parameter.setStyleSheet("border: 3px solid white;")
        self.pump2_parameter.setObjectName("pump2_parameter")
        self.pump1_parameter_down01 = QtWidgets.QPushButton(self.frame_6)
        self.pump1_parameter_down01.setGeometry(QtCore.QRect(40, 310, 61, 61))
        self.pump1_parameter_down01.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/아래삼각형.png);\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/아래삼각형_pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.pump1_parameter_down01.setText("")
        self.pump1_parameter_down01.setObjectName("pump1_parameter_down01")
        self.pump2_parameter_down05 = QtWidgets.QPushButton(self.frame_6)
        self.pump2_parameter_down05.setGeometry(QtCore.QRect(290, 310, 61, 61))
        self.pump2_parameter_down05.setStyleSheet("QPushButton{\n"
"border: none;\n"
"    \n"
"    image: url(:/newPrefix/아래삼각형2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/아래삼각형2 _pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.pump2_parameter_down05.setText("")
        self.pump2_parameter_down05.setObjectName("pump2_parameter_down05")
        self.pump2_parameter_up05 = QtWidgets.QPushButton(self.frame_6)
        self.pump2_parameter_up05.setGeometry(QtCore.QRect(290, 240, 61, 61))
        self.pump2_parameter_up05.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/위삼각형2.png);\n"
"border: none;\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/위삼각형2_pressed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.pump2_parameter_up05.setText("")
        self.pump2_parameter_up05.setObjectName("pump2_parameter_up05")
        self.pump1_parameter_up01 = QtWidgets.QPushButton(self.frame_6)
        self.pump1_parameter_up01.setGeometry(QtCore.QRect(40, 240, 61, 61))
        self.pump1_parameter_up01.setStyleSheet("QPushButton{\n"
"image: url(:/newPrefix/위삼각형.png);\n"
"border: none;\n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    image: url(:/newPrefix/위삼각형_preesed.png);\n"
"    border:none;\n"
"    outline: none;\n"
"}")
        self.pump1_parameter_up01.setText("")
        self.pump1_parameter_up01.setObjectName("pump1_parameter_up01")
        self.pump1_parameter = QtWidgets.QLCDNumber(self.frame_6)
        self.pump1_parameter.setGeometry(QtCore.QRect(40, 80, 141, 151))
        self.pump1_parameter.setStyleSheet("border: 3px solid white;")
        self.pump1_parameter.setObjectName("pump1_parameter")
        self.horizontalLayout_11.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.page_parameter)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_11.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_parameter)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.comboBox = QtWidgets.QComboBox(self.page_settings)
        self.comboBox.setGeometry(QtCore.QRect(100, 70, 241, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"border: 1px solid white;\n"
"padding:1px 0px 1px 3px;\n"
"\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.page_settings)
        self.pushButton.setGeometry(QtCore.QRect(440, 70, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:1px solid white;")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_settings)
        self.horizontalLayout_9.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_content)
        self.frame_grip = QtWidgets.QFrame(self.frame_content_right)
        self.frame_grip.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_grip.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_grip.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_grip)
        self.horizontalLayout_6.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_label_bottom = QtWidgets.QFrame(self.frame_grip)
        self.frame_label_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6.addWidget(self.frame_label_bottom)
        self.frame_size_grip = QtWidgets.QFrame(self.frame_grip)
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_size_grip.setStyleSheet("QSizeGrip {\n"
"    background-image: url(:/16x16/icons/16x16/cil-size-grip.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"}")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_6.addWidget(self.frame_size_grip)
        self.verticalLayout_4.addWidget(self.frame_grip)
        self.horizontalLayout_2.addWidget(self.frame_content_right)
        self.verticalLayout.addWidget(self.frame_center)
        self.horizontalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title_bar_top.setText(_translate("MainWindow", "K-CocktailMate"))
        self.btn_back.setToolTip(_translate("MainWindow", "Close"))
        self.start_button.setText(_translate("MainWindow", "제조 시작"))
        self.drink1_replace_button.setText(_translate("MainWindow", "교체"))
        self.drink2_replace_button.setText(_translate("MainWindow", "교체"))
        self.drink1_residual_label.setText(_translate("MainWindow", "360ml"))
        self.drink2_residual_label.setText(_translate("MainWindow", "500ml"))
        self.label_3.setText(_translate("MainWindow", "2번 펌프 출력양"))
        self.label.setText(_translate("MainWindow", "1번 펌프 출력양"))
        self.comboBox.setItemText(0, _translate("MainWindow", "소리 켜기"))
        self.comboBox.setItemText(1, _translate("MainWindow", "소리 끄기"))
        self.pushButton.setText(_translate("MainWindow", "현재 설정값   \n"
"기본값으로 저장"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
