# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_version1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Toggle_Bar = QtWidgets.QFrame(self.Top_Bar)
        self.Toggle_Bar.setMaximumSize(QtCore.QSize(70, 40))
        self.Toggle_Bar.setStyleSheet("background-color: rgb(35, 94, 255);")
        self.Toggle_Bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Toggle_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Toggle_Bar.setObjectName("Toggle_Bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Toggle_Bar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.Toggle_Bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Btn_Toggle.setFont(font)
        self.Btn_Toggle.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.Toggle_Bar)
        self.Top_frame = QtWidgets.QFrame(self.Top_Bar)
        self.Top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_frame.setObjectName("Top_frame")
        self.horizontalLayout.addWidget(self.Top_frame)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_leftmenu = QtWidgets.QFrame(self.Content)
        self.frame_leftmenu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_leftmenu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_leftmenu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_leftmenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_leftmenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_leftmenu.setObjectName("frame_leftmenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_leftmenu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_leftmenu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.home_btn = QtWidgets.QPushButton(self.frame_top_menus)
        self.home_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.home_btn.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Calibri\";\n"
"border: 0px solid;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(0, 85, 255);\n"
"}")
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout_4.addWidget(self.home_btn)
        self.monitor_btn = QtWidgets.QPushButton(self.frame_top_menus)
        self.monitor_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.monitor_btn.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Calibri\";\n"
"border: 0px solid;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(0, 85, 255);\n"
"}")
        self.monitor_btn.setObjectName("monitor_btn")
        self.verticalLayout_4.addWidget(self.monitor_btn)
        self.setting_btn = QtWidgets.QPushButton(self.frame_top_menus)
        self.setting_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.setting_btn.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Calibri\";\n"
"border: 0px solid;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(0, 85, 255);\n"
"}")
        self.setting_btn.setObjectName("setting_btn")
        self.verticalLayout_4.addWidget(self.setting_btn)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_leftmenu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.up1_btn = QtWidgets.QPushButton(self.home_page)
        self.up1_btn.setGeometry(QtCore.QRect(170, 230, 131, 51))
        self.up1_btn.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.up1_btn.setAutoDefault(False)
        self.up1_btn.setObjectName("up1_btn")
        self.up2_btn = QtWidgets.QPushButton(self.home_page)
        self.up2_btn.setGeometry(QtCore.QRect(410, 230, 131, 51))
        self.up2_btn.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.up2_btn.setObjectName("up2_btn")
        self.start_btn = QtWidgets.QPushButton(self.home_page)
        self.start_btn.setGeometry(QtCore.QRect(280, 310, 151, 71))
        self.start_btn.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.display_first_percent = QtWidgets.QLCDNumber(self.home_page)
        self.display_first_percent.setGeometry(QtCore.QRect(200, 50, 64, 151))
        self.display_first_percent.setObjectName("display_first_percent")
        self.display_second_percent = QtWidgets.QLCDNumber(self.home_page)
        self.display_second_percent.setGeometry(QtCore.QRect(440, 50, 64, 151))
        self.display_second_percent.setObjectName("display_second_percent")
        self.Pages_Widget.addWidget(self.home_page)
        self.monitor_page = QtWidgets.QWidget()
        self.monitor_page.setObjectName("monitor_page")
        self.temperature_display = QtWidgets.QLCDNumber(self.monitor_page)
        self.temperature_display.setGeometry(QtCore.QRect(140, 90, 161, 111))
        self.temperature_display.setObjectName("temperature_display")
        self.Pages_Widget.addWidget(self.monitor_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.textBrowser = QtWidgets.QTextBrowser(self.setting_page)
        self.textBrowser.setGeometry(QtCore.QRect(160, 90, 421, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.Pages_Widget.addWidget(self.setting_page)
        self.verticalLayout_5.addWidget(self.Pages_Widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_Widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setText(_translate("MainWindow", "MENU"))
        self.home_btn.setText(_translate("MainWindow", "HOME"))
        self.monitor_btn.setText(_translate("MainWindow", "MONITOR"))
        self.setting_btn.setText(_translate("MainWindow", "SETTING"))
        self.up1_btn.setText(_translate("MainWindow", "UP1"))
        self.up2_btn.setText(_translate("MainWindow", "UP2"))
        self.start_btn.setText(_translate("MainWindow", "START"))
        self.display_first_percent.display(_translate("MainWindow", "30"))
        self.display_second_percent.display(_translate("MainWindow", "70"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">setting page</span></p></body></html>"))
